In [6]:
import numpy as np

In [8]:
myarr=np.array([3,6,32,7])

In [9]:
myarr

array([ 3,  6, 32,  7])

In [12]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]]) 

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(1,4,5)

In [20]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [21]:
emp=np.empty((4,6))

In [22]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.11260483e-306,
        4.45055939e-308, 7.56599128e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37960147e-306, 1.33511562e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306, 1.24611402e-306],
       [1.33512173e-306, 1.11261570e-306, 8.90092016e-307,
        1.37961302e-306, 2.22522868e-306, 2.56765117e-312]])

In [25]:
matrix=np.identity(3)


In [26]:
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [28]:
ar=np.array(x)

In [29]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [30]:
ar.sum()

29

In [31]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [32]:
ar.flat

In [33]:
ar.ndim

2

In [34]:
ar.size

9

In [35]:
ar.argmax()

6

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar1=[[1,2,3],[4,5,6],[7,1,0]]

In [38]:
ar+ar1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [39]:
ar*ar1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [40]:
import sys

In [41]:
ch_ar=[0,4,55,2]

In [42]:
py_ar=[0,4,55,2]

In [43]:
np_ar=np.array(py_ar)

In [44]:
sys.getsizeof(1)

28

In [45]:
np_ar.itemsize 

4